server:
    type: simple
    applicationContextPath: /
    rootPath: /api/
    connector:
        type: http
        port: 8080

assets:
  overrides:
    /web-client: src/main/resources/web-client/

logging:
  level: INFO
  loggers:
    fr.jbrunet.dw.websocket.example: DEBUG
